import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Animated, Easing, FlatList, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
type Track = { id: string; title: string; artist: string; uri: string; duration: number; kind: 'audio' | 'video'; folder: string; category: 'Melody' | 'Fast Beats' | 'Other' };
type Stats = Record<string, { plays: number; completed: number; lastPlayedAt: number }>;
const accent = '#A7F36B';
export function MediaBrowser(p: { kind: 'audio' | 'video'; items: Track[]; stats: Stats; favourites: string[]; onFavourite(id: string): void; onPlay(t: Track, list: Track[]): void; scanning: boolean; onScan(): void; excluded: number; shuffle: boolean; onShuffle(): void; onRandom(list: Track[]): void; onHideFolder(folder: string): void; dedicatedFolder: string; theme: { panel: string; accent: string } }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('All');
  const [folder, setFolder] = useState('All folders');
  const source = p.items.filter(t => t.kind === p.kind);
  const folders = ['All folders', ...new Set(source.map(t => t.folder))];
  const rows = useMemo(() => {
    let result = source.filter(t => (folder === 'All folders' || t.folder === folder) && (t.title + ' ' + t.folder).toLowerCase().includes(query.toLowerCase()));
    if (filter === 'Favourites') result = result.filter(t => p.favourites.includes(t.id));
    if (filter === 'Most played') result = result.filter(t => (p.stats[t.id]?.plays || 0) > 0).sort((a,b) => (p.stats[b.id]?.plays || 0) - (p.stats[a.id]?.plays || 0));
    if (filter === 'Least played') result.sort((a,b) => (p.stats[a.id]?.plays || 0) - (p.stats[b.id]?.plays || 0));
    if (filter === 'Melody') result = result.filter(t => t.category === 'Melody');
    if (filter === 'Fast Beats') result = result.filter(t => t.category === 'Fast Beats');
    if (filter === 'Other') result = result.filter(t => t.category === 'Other');
    return result;
  }, [p.items, folder, query, filter, p.stats, p.favourites, p.kind]);
  return <FlatList data={rows} keyExtractor={t => t.id} contentContainerStyle={{ padding: 18, paddingBottom: 30 }} ListHeaderComponent={<>
    <View style={[s.hero,{backgroundColor:p.theme.panel}]}><Text style={[s.kicker,{color:p.theme.accent}]}>YOUR PERSONAL COLLECTION</Text><View style={s.row}><Text style={s.title}>{p.kind === 'audio' ? 'Music' : 'Video'}</Text><Ionicons name={p.kind === 'audio' ? 'headset' : 'film'} size={52} color={p.theme.accent} /></View><Text style={s.sub}>{source.length} {p.kind === 'audio' ? 'songs' : 'videos'} · {p.favourites.filter(id => source.some(t => t.id === id)).length} favourites</Text></View>
    {p.kind === 'audio' && <View style={s.musicActions}><Pressable onPress={p.onShuffle} style={[s.actionButton, p.shuffle && s.actionActive]}><Ionicons name="shuffle" size={20} color={p.shuffle ? '#131B13' : accent} /><Text style={[s.actionText, p.shuffle && {color:'#131B13'}]}>{p.shuffle ? 'Stop random' : 'Shuffle off'}</Text></Pressable><Pressable onPress={() => p.onRandom(rows)} style={[s.actionButton,p.shuffle && s.randomActive]}><Ionicons name="dice-outline" size={21} color={p.shuffle?'#131B13':accent} /><Text style={[s.actionText,p.shuffle&&{color:'#131B13'}]}>{p.shuffle?'Random playing':'Play random'}</Text></Pressable></View>}
    {p.kind === 'audio' && <View style={[s.folderFocus,{backgroundColor:p.theme.panel}]}><Ionicons name="folder-open-outline" size={22} color={p.theme.accent} /><View style={{flex:1}}><Text style={s.name}>{p.dedicatedFolder} folder</Text><Text style={s.sub}>{source.some(track => track.folder === p.dedicatedFolder) ? 'Tap to show only songs from your dedicated folder.' : `Put songs in Music/${p.dedicatedFolder}, then tap Refresh.`}</Text></View><Pressable disabled={!source.some(track => track.folder === p.dedicatedFolder)} onPress={() => setFolder(p.dedicatedFolder)} style={s.focusButton}><Text style={{color:p.theme.accent,fontWeight:'800'}}>Open</Text></Pressable></View>}
    <TextInput style={s.input} placeholder="Search titles or folders" placeholderTextColor="#929B91" value={query} onChangeText={setQuery} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false}>{['All','Favourites','Most played','Least played', ...(p.kind === 'audio' ? ['Melody','Fast Beats','Other'] : [])].map(name => <Pressable key={name} onPress={() => setFilter(name)} style={[s.chip, filter === name && s.selected]}><Text style={{ color: filter === name ? '#131B13' : '#ddd' }}>{name}</Text></Pressable>)}</ScrollView>
    <ScrollView horizontal showsHorizontalScrollIndicator={false}>{folders.map(name => <Pressable key={name} onPress={() => setFolder(name)} style={s.chip}><Text style={{ color: folder === name ? accent : '#929B91' }}>▱ {name}</Text></Pressable>)}</ScrollView>
    {p.kind === 'audio' && folder !== 'All folders' && <Pressable onPress={() => { p.onHideFolder(folder); setFolder('All folders'); }} style={s.hideButton}><Ionicons name="eye-off-outline" color="#FF9A86" size={17} /><Text style={s.hideText}>Hide every audio file from “{folder}”</Text></Pressable>}
    <View style={s.row}><Text style={s.sub}>{p.scanning ? (source.length ? 'Updating library in background…' : 'Loading device media…') : `${rows.length} items`}</Text><Pressable onPress={p.onScan}><Text style={{ color: accent }}>Refresh ↻</Text></Pressable></View>
    {p.kind === 'audio' && <Text style={s.smartNote}>Smart groups use song and folder names; unknown songs stay in Other.</Text>}
    {p.kind === 'audio' && p.excluded > 0 && <Text style={s.sub}>{p.excluded} messaging/call recordings hidden</Text>}
  </>} ListEmptyComponent={<Text style={[s.sub,{ paddingVertical: 35 }]}>{p.scanning ? 'Scanning all accessible folders…' : filter === 'Most played' ? 'Play songs to build your listening history.' : filter === 'Favourites' ? 'Tap a heart beside any song or video to save it here.' : 'No matching files. Check Android media permissions, then tap Refresh.'}</Text>}
    renderItem={({ item, index }) => <View style={s.media}><Pressable onPress={() => p.onPlay(item, rows)} style={[s.row,{flex:1, gap:12}]}><View style={[s.cover,{backgroundColor:['#314F3B','#443852','#4E3E2A'][index%3]}]}><Ionicons name={p.kind === 'audio' ? 'musical-note' : 'play-circle'} color={accent} size={26} /></View><View style={{flex:1}}><Text numberOfLines={2} style={s.name}>{item.title}</Text><Text numberOfLines={1} style={s.sub}>{item.folder} · {Math.floor(item.duration/60)}:{String(Math.floor(item.duration%60)).padStart(2,'0')} · {p.stats[item.id]?.plays || 0} plays</Text>{p.kind === 'audio' && item.category !== 'Other' && <Text style={s.category}>{item.category === 'Fast Beats' ? '⚡' : '♪'} {item.category}</Text>}</View></Pressable><Pressable accessibilityLabel="Toggle favourite" onPress={() => p.onFavourite(item.id)} style={{padding:12}}><Ionicons name={p.favourites.includes(item.id) ? 'heart' : 'heart-outline'} color={p.favourites.includes(item.id) ? '#FF8DAB' : '#9CA69B'} size={23} /></Pressable></View>} />;
}

function Fader(p: { label: string; hint?: string; value: number; min?: number; max?: number; step?: number; change(v: number): void; format?(v: number): string; color?: string }) {
 const min = p.min ?? 0; const max = p.max ?? 1; const [width, setWidth] = useState(1);
 const update = (x: number) => { const raw = min + Math.max(0, Math.min(1, x / width)) * (max - min); const step = p.step || .01; p.change(Math.round(raw / step) * step); };
 const percent = Math.max(0, Math.min(100, (p.value - min) / (max - min) * 100));
 return <View style={s.fader}><View style={s.row}><View><Text style={s.name}>{p.label}</Text>{p.hint && <Text style={s.controlHint}>{p.hint}</Text>}</View><Text style={[s.readout,{color:p.color || accent}]}>{p.format ? p.format(p.value) : `${Math.round(p.value * 100)}%`}</Text></View><View accessibilityRole="adjustable" accessibilityLabel={p.label} onLayout={e => setWidth(e.nativeEvent.layout.width)} onStartShouldSetResponder={() => true} onMoveShouldSetResponder={() => true} onResponderGrant={e => update(e.nativeEvent.locationX)} onResponderMove={e => update(e.nativeEvent.locationX)} style={s.faderTouch}><View style={s.faderTrack}><View style={[s.faderFill,{width:`${percent}%`,backgroundColor:p.color || accent}]} /><View style={[s.faderThumb,{left:`${percent}%`,borderColor:p.color || accent}]} /></View></View></View>;
}

function VuScreen({ levels, spectrum, ready, playing, color }: { levels: number[]; spectrum: number[]; ready: boolean; playing: boolean; color: string }) {
 const db = (level: number) => level > 0 ? Math.max(-60, 20 * Math.log10(level)) : -60;
 const active = ready && playing;
 return <><View style={s.vuCard}><View style={s.vuHeader}><View><Text style={s.vuTitle}>LIVE OUTPUT</Text><Text style={s.vuSub}>{active ? 'Real playback waveform' : ready ? 'Start a song to meter its output' : 'Allow microphone permission for Android playback sampling'}</Text></View><View style={[s.signalDot,{backgroundColor:active?'#83F28F':'#697168'}]} /></View><View style={s.bigSpectrum}>{spectrum.map((value,index)=><View key={index} style={[s.bigBar,{height:`${Math.max(4,(active?value:0)*100)}%`,backgroundColor:index > 14 ? '#FF6B67' : index > 10 ? '#FFD166' : color}]} />)}</View><Text style={s.scale}>-60       -30       -18       -12        -6         0 dB</Text></View>{['LEFT','RIGHT'].map((label,index)=>{const level=active?(levels[index]||0):0;return <View key={label} style={s.channel}><Text style={s.channelName}>{label}</Text><View style={s.leds}>{Array.from({length:20},(_,i)=><View key={i} style={[s.led,{backgroundColor:i/20<=level?(i>17?'#FF5D67':i>13?'#FFD166':color):'#303832'}]} />)}</View><Text style={s.dbText}>{db(level).toFixed(1)}</Text></View>})}<View style={s.meterNote}><Ionicons name="information-circle-outline" size={18} color={color}/><Text style={s.meterNoteText}>The meter analyzes this app’s playback session only. It never records or stores microphone audio.</Text></View></>;
}

type SoundPanelProps = { visible: boolean; onClose(): void; gains: number[]; setGains(v: number[]): void; enabled: boolean; setEnabled(v: boolean): void; status: string; volume: number; setVolume(v: number): void; bassBoost: number; setBassBoost(v: number): void; clarity: number; setClarity(v: number): void; spatial: number; setSpatial(v: number): void; loudness: number; setLoudness(v: number): void; hearingProtect: boolean; setHearingProtect(v: boolean): void; playbackRate: number; setPlaybackRate(v: number): void; levels: number[]; spectrum: number[]; meterReady: boolean; playing: boolean; theme: { background: string; panel: string; accent: string } };
export function SoundPanel(p: SoundPanelProps) {
 const [page,setPage]=useState<'Meter'|'EQ'|'Enhancer'|'Mixer'>('Meter');
 const presets=[{name:'Flat',icon:'remove-outline' as const,g:[0,0,0,0,0],bass:.1,clear:.1},{name:'Deep',icon:'pulse-outline' as const,g:[4,2,0,-1,0],bass:.65,clear:.12},{name:'Vocal',icon:'mic-outline' as const,g:[-2,-1,2,4,2],bass:.05,clear:.65},{name:'Bright',icon:'sunny-outline' as const,g:[-1,0,1,3,5],bass:.05,clear:.45},{name:'Warm',icon:'flame-outline' as const,g:[3,2,1,0,-1],bass:.35,clear:.18},{name:'Night',icon:'moon-outline' as const,g:[1,1,0,1,0],bass:.15,clear:.25}];
 const applyPreset=(preset:typeof presets[number])=>{p.setEnabled(true);p.setGains(preset.g);p.setBassBoost(preset.bass);p.setClarity(preset.clear)};
 return <Modal visible={p.visible} animationType="slide" onRequestClose={p.onClose}><SafeAreaProvider><SafeAreaView style={{flex:1,backgroundColor:p.theme.background}}><View style={s.studioHeader}><View><Text style={s.studioKicker}>PULSE DSP ENGINE</Text><Text style={s.studioTitle}>Sound studio</Text></View><Pressable accessibilityLabel="Close sound studio" onPress={p.onClose} style={[s.closeButton,{backgroundColor:p.theme.panel}]}><Ionicons name="close" size={23} color="#F3F7EA" /></Pressable></View><View style={[s.studioTabs,{backgroundColor:p.theme.panel}]}>{(['Meter','EQ','Enhancer','Mixer'] as const).map(name=><Pressable key={name} onPress={()=>setPage(name)} style={[s.studioTab,page===name&&{backgroundColor:p.theme.accent}]}><Ionicons name={({Meter:'speedometer-outline',EQ:'options-outline',Enhancer:'sparkles-outline',Mixer:'git-compare-outline'} as const)[name]} size={17} color={page===name?'#11160F':'#A9B2A4'} /><Text style={[s.studioTabText,page===name&&{color:'#11160F'}]}>{name}</Text></Pressable>)}</View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.studioBody}>
 {page==='Meter'&&<VuScreen levels={p.levels} spectrum={p.spectrum} ready={p.meterReady} playing={p.playing} color={p.theme.accent} />}
 {page==='EQ'&&<><View style={s.sectionHead}><View><Text style={s.panelTitle}>Parametric feel</Text><Text style={s.panelSub}>Five musical zones mapped to your device EQ bands</Text></View><Switch value={p.enabled} onValueChange={p.setEnabled} thumbColor="#fff" trackColor={{false:'#4B504A',true:p.theme.accent}} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingVertical:8}}>{presets.map(preset=><Pressable key={preset.name} onPress={()=>applyPreset(preset)} style={[s.preset,{backgroundColor:p.theme.panel}]}><Ionicons name={preset.icon} size={19} color={p.theme.accent}/><Text style={s.presetText}>{preset.name}</Text></Pressable>)}</ScrollView>{['Sub bass · 60 Hz','Body · 230 Hz','Detail · 910 Hz','Presence · 3.6 kHz','Air · 14 kHz'].map((label,i)=><Fader key={label} label={label} value={p.gains[i]||0} min={-12} max={12} step={.5} format={v=>`${v>0?'+':''}${v.toFixed(1)} dB`} change={v=>p.setGains(p.gains.map((old,j)=>i===j?v:old))} color={p.theme.accent}/>)}</>}
 {page==='Enhancer'&&<><Text style={s.panelTitle}>Enhancement rack</Text><Text style={s.panelSub}>Hardware-assisted effects attached directly to this playback session</Text><View style={[s.engineCard,{backgroundColor:p.theme.panel}]}><Fader label="Bass impact" hint="Android BassBoost · best with headphones" value={p.bassBoost} change={p.setBassBoost} color="#FF8C69"/><Fader label="Clarity" hint="Presence detail without harsh treble" value={p.clarity} change={p.setClarity} color="#79D7FF"/><Fader label="Spatial width" hint="Stereo virtualizer · output support varies" value={p.spatial} change={p.setSpatial} color="#BE9BFF"/><Fader label="Loudness" hint="Raises quiet playback; keep protection on" value={p.loudness} change={p.setLoudness} color="#FFD166"/></View><View style={[s.protectCard,{borderColor:p.hearingProtect?p.theme.accent:'#444'}]}><View style={s.protectIcon}><Ionicons name="shield-checkmark" size={22} color={p.theme.accent}/></View><View style={{flex:1}}><Text style={s.name}>Clipping protection</Text><Text style={s.controlHint}>Limits enhancer gain when EQ bands are boosted</Text></View><Switch value={p.hearingProtect} onValueChange={p.setHearingProtect}/></View></>}
 {page==='Mixer'&&<><Text style={s.panelTitle}>Output mixer</Text><Text style={s.panelSub}>Fast, precise controls for the active music session</Text><View style={[s.engineCard,{backgroundColor:p.theme.panel}]}><Fader label="Player volume" hint="Separate from your phone’s media volume" value={p.volume} change={p.setVolume} color={p.theme.accent}/><Fader label="Playback speed" hint="Pitch correction stays enabled" value={p.playbackRate} min={.75} max={1.5} step={.05} format={v=>`${v.toFixed(2)}×`} change={p.setPlaybackRate} color="#79D7FF"/></View><View style={s.quickRow}>{[.8,1,1.1,1.25].map(value=><Pressable key={value} onPress={()=>p.setPlaybackRate(value)} style={[s.speedButton,p.playbackRate===value&&{backgroundColor:p.theme.accent}]}><Text style={[s.speedText,p.playbackRate===value&&{color:'#11160F'}]}>{value}×</Text></Pressable>)}</View><Text style={s.panelFoot}>Pulse keeps Android audio mixing enabled so YouTube can continue playing. Bluetooth/phone-speaker separation remains controlled by iQOO Audio Redirect.</Text></>}
 </ScrollView><View style={[s.engineStatus,{backgroundColor:p.theme.panel}]}><View style={[s.signalDot,{backgroundColor:p.status.includes('active')?'#83F28F':'#FFD166'}]}/><Text numberOfLines={1} style={s.engineStatusText}>{p.status}</Text></View></SafeAreaView></SafeAreaProvider></Modal>;
}
const s=StyleSheet.create({hero:{padding:22,borderRadius:28,backgroundColor:'#253629',marginBottom:16},kicker:{color:accent,fontSize:9,letterSpacing:2,fontWeight:'800'},title:{color:'#F3F7EA',fontSize:38,fontWeight:'900',letterSpacing:-1},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},sub:{color:'#A9B2A4',fontSize:11,lineHeight:17,marginTop:5},smartNote:{color:'#788375',fontSize:9,lineHeight:14,marginTop:5},input:{backgroundColor:'#252B24',borderRadius:16,padding:15,color:'#fff',marginBottom:9},chip:{paddingHorizontal:14,paddingVertical:10,backgroundColor:'#293127',borderRadius:14,marginRight:7,marginVertical:5},selected:{backgroundColor:accent},musicActions:{flexDirection:'row',gap:9,marginBottom:12},actionButton:{flex:1,minHeight:48,borderRadius:16,borderWidth:1,borderColor:'#40533F',backgroundColor:'#222D24',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},actionActive:{backgroundColor:accent,borderColor:accent},randomActive:{backgroundColor:'#79D7FF',borderColor:'#79D7FF'},actionText:{color:'#F1F5E8',fontWeight:'800',fontSize:12},folderFocus:{flexDirection:'row',alignItems:'center',gap:11,padding:14,borderRadius:18,backgroundColor:'#1D2920',marginBottom:12},focusButton:{paddingHorizontal:10,paddingVertical:11},hideButton:{minHeight:44,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,marginBottom:8},hideText:{color:'#FF9A86',fontSize:11,fontWeight:'800'},media:{flexDirection:'row',alignItems:'center',paddingVertical:13,borderBottomWidth:1,borderBottomColor:'#2D342A'},cover:{width:58,height:62,borderRadius:17,alignItems:'center',justifyContent:'center'},name:{color:'#F1F5E8',fontSize:14,fontWeight:'700'},category:{color:accent,fontSize:9,fontWeight:'800'},
 studioHeader:{paddingHorizontal:20,paddingTop:12,paddingBottom:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},studioKicker:{color:accent,fontSize:9,fontWeight:'900',letterSpacing:2},studioTitle:{color:'#F3F7EA',fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:2},closeButton:{width:44,height:44,borderRadius:16,alignItems:'center',justifyContent:'center'},studioTabs:{flexDirection:'row',marginHorizontal:14,padding:5,borderRadius:19},studioTab:{flex:1,minHeight:52,borderRadius:15,alignItems:'center',justifyContent:'center',gap:3},studioTabText:{color:'#A9B2A4',fontSize:9,fontWeight:'800'},studioBody:{padding:18,paddingBottom:104},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:7},panelTitle:{color:'#F3F7EA',fontSize:24,fontWeight:'900',letterSpacing:-.5},panelSub:{color:'#97A096',fontSize:11,lineHeight:17,marginTop:4,marginBottom:12},panelFoot:{color:'#818A81',fontSize:10,lineHeight:16,marginTop:18},
 vuCard:{height:285,borderRadius:28,backgroundColor:'#161E19',borderWidth:1,borderColor:'#344238',padding:18,overflow:'hidden'},vuHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},vuTitle:{color:'#F3F7EA',fontSize:13,fontWeight:'900',letterSpacing:1.4},vuSub:{color:'#879188',fontSize:9,marginTop:3},signalDot:{width:9,height:9,borderRadius:5},bigSpectrum:{height:180,flexDirection:'row',alignItems:'flex-end',gap:4,paddingTop:20},bigBar:{flex:1,minHeight:4,borderRadius:5},scale:{color:'#667068',fontSize:7,letterSpacing:.2,marginTop:10},channel:{height:54,flexDirection:'row',alignItems:'center',gap:9,marginTop:10},channelName:{color:'#9AA39A',fontSize:9,fontWeight:'900',width:35},leds:{flex:1,flexDirection:'row',gap:3},led:{height:14,flex:1,borderRadius:3},dbText:{color:'#F3F7EA',fontVariant:['tabular-nums'],fontSize:10,width:38,textAlign:'right'},meterNote:{flexDirection:'row',gap:9,backgroundColor:'#202923',padding:13,borderRadius:16,marginTop:14},meterNoteText:{color:'#9AA39A',fontSize:9,lineHeight:14,flex:1},
 fader:{marginVertical:10},controlHint:{color:'#7F897F',fontSize:9,marginTop:3},readout:{fontSize:12,fontWeight:'900',fontVariant:['tabular-nums']},faderTouch:{height:30,justifyContent:'center'},faderTrack:{height:7,borderRadius:5,backgroundColor:'#3A433C'},faderFill:{height:7,borderRadius:5},faderThumb:{position:'absolute',top:-7,marginLeft:-10,width:21,height:21,borderRadius:11,backgroundColor:'#F5F8F0',borderWidth:3},preset:{width:78,height:72,borderRadius:19,alignItems:'center',justifyContent:'center',gap:6,marginRight:9},presetText:{color:'#EEF3E9',fontSize:10,fontWeight:'800'},engineCard:{padding:17,borderRadius:24,borderWidth:1,borderColor:'#343E36'},protectCard:{flexDirection:'row',alignItems:'center',gap:11,padding:15,borderRadius:20,borderWidth:1,marginTop:14},protectIcon:{width:42,height:42,borderRadius:15,backgroundColor:'#29352D',alignItems:'center',justifyContent:'center'},quickRow:{flexDirection:'row',gap:8,marginTop:13},speedButton:{flex:1,height:44,borderRadius:14,backgroundColor:'#29312B',alignItems:'center',justifyContent:'center'},speedText:{color:'#E9EFE5',fontSize:11,fontWeight:'900'},engineStatus:{position:'absolute',bottom:0,left:0,right:0,minHeight:58,borderTopWidth:1,borderTopColor:'#343C36',flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:19},engineStatusText:{color:'#A8B1A7',fontSize:10,flex:1}
});
